# Site settings
title: New Age Test Page
email:
description: A jekyll template for landing pages, portfolio and blogging

baseurl: "/new-age-test" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
